version: 2
updates:
  # Enable version updates for pnpm (using npm ecosystem)
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check for updates once a week
    schedule:
      interval: 'weekly'
    # Specify labels for pnpm pull requests
    labels:
      - 'pnpm'
      - 'dependencies'
    # Set reviewers for pull requests
    reviewers:
      - 'kosuke'
    # Limit the number of open pull requests for npm dependencies
    open-pull-requests-limit: 10
    # Allow only production dependencies to be updated
    allow:
      - dependency-type: 'production'
    # Group all minor and patch updates together
    groups:
      dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'github-actions'
      - 'dependencies'
    reviewers:
      - 'kosuke'
    open-pull-requests-limit: 5
