version: '3.8'

services:
  postgres:
    image: postgres:16.4-alpine
    container_name: kosuke_template_postgres
    env_file:
      - .env
    ports:
      - '54321:5432'
    volumes:
      - kosuke_template_postgres_data:/var/lib/postgresql/data

  engine:
    build:
      context: ./engine
      dockerfile: Dockerfile
    container_name: kosuke_template_engine
    ports:
      - '8000:8000'
    volumes:
      - ./engine:/app
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

volumes:
  kosuke_template_postgres_data:
